[theme]
primaryColor = "#5859DC"
backgroundColor = "#F6F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#10172B"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
